config = {
    "seed": 42,
    "epochs": 500,
    "batch_size": 64,
    "lr_G": 1e-3,
    "lr_D": 1e-3,
    "lambda_cls": 2.0,
    "lambda_reg_l1": 5.0,
    "lambda_reg_l2": 5.0,
    "lambda_mask": 3.0,
    "input_dim": 2,
    "hidden_dim": 32,
    "out_dir": "results",
    "clf_model_path": "results/classifier.pt",
    "generator_path": "results/generator.pt",
    "cuda": "cuda" if __import__("torch").cuda.is_available() else "cpu",
}